on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ronazohar.co.il
          username: u582912709
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.git*
            **/.github/**
          server-dir: public_html/